default: &default
    adapter: postgresql
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000

development:
    <<: *default
    host: postgres
    username: postgres
    database: railsfront_development

test:
    <<: *default
    host: postgres
    username: postgres
    database: railsfront_test

production:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
