source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "3.0.2"

gem "rails", "~> 6.1.4", ">= 6.1.4.1"
gem "bootsnap", ">= 1.4.4", require: false
gem "devise"
gem "devise-jwt"
gem "foreman"
gem "jsonapi-rails"
gem "pg", "~> 1.1"
gem "puma", "~> 5.0"
gem "rack-cors"
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  gem "byebug", platforms: [:mri, :mingw, :x64_mingw]
  gem "rspec-rails", "~> 3.8"
  gem "factory_bot_rails"
  gem "pry-byebug"
  gem "pry-rails"
end

group :development do
  gem "listen", "~> 3.3"
  gem "rubocop"
  gem "solargraph"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
  gem "web-console", ">= 3.3.0"
end

group :test do
  gem "capybara", ">= 2.15"
  gem "faker"
  gem "selenium-webdriver"
  gem "shoulda-matchers", "~> 4.0"
  gem "vcr"
  gem "webdrivers"
  gem "jsonapi-rspec"
  gem "webmock"
end
